apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  tridentImage: quay.io/pradeepkumar27x/trident:26.06.0-custom-linux-amd64
  imagePullSecrets:
  - thisisasecret
